### ISSUE TITLE
Problème au niveau des dates

### ISSUE THREAD

**Issue by Mides** [GarenKreiz/Geocaching-Journal#21]
Si deux enregistrements possèdent la même date de log un bug est déclenché. La date ne figure plus dans l'enregistrement du fichier xml de base ce qui peut poser problème pour la génération du fichier final en html.  La déclaration de la variable days{} de type dictionnaire n'est peut être pas l'idéal, même si une gestion d'exception existe,  et il vaut peut être mieux passer par une liste pour la robustesse du code. 

```
# -*- coding: utf-8 -*-

import pprint

logs = ['2004/01/01', '2004/02/01', '2004/01/01', '2004/06/01']
days = {}
for dateLog in logs:
    try:
        days[dateLog].append(('RETZE-LKFMLSF-4564545S', '474SHFJSDHF-SLKDF-SDF', 'test', 'Found', 'C'))
    except:
        days[dateLog] = [('RETZE-LKFMLSF-4564545S', '474SHFJSDHF-SLKDF-SDF', 'test', 'Found', 'C')]
print '--Dictionnaire--'        
print pprint.pprint(days) 


days = []
for dateLog in logs:
    days.append((dateLog, 'RETZE-LKFMLSF-4564545S', '474SHFJSDHF-SLKDF-SDF', 'test', 'Found', 'C'))
print '--liste--'
print pprint.pprint(days) 
```

**Comment by GarenKreiz** [comment]
Il ne me semble pas avoir observé de pb sur ce point. Ci-joint un exemple de fichier XML généré avec plusieurs entrées sur une journée.

[logbook.xml](https://github.com/GarenKreiz/Geocaching-Journal/files/608847/logbook.xml.txt)

**Comment by Mides** [comment]
Ok vu ! je n'ai pas la vue globale du "xml2print' et je comprends un peu mieux maintenant avec cet exemple qui me confirme l'absence de balise date entre certains logs. 
En définitive, les enregistrements logs sur une même journées sont regroupés et n'y figure pas la balise <date> entre eux. Je suppose que "xml2print" se base sur cette balise pour effectuer les ruptures. 
c'est la construction du dictionnaire avec comme valeur une liste de 1 à n tuple qui me perturbait. :-)

**Comment by Mides** [comment]
Est-ce que je peux proposer cette modif, ça me perturbera peut être un peu moins. ahahah 

```
if dateLog in days:
    days[dateLog].append((idLog, idCache, titleCache, typeLog, natureLog))
else:
    days[dateLog] = [(idLog, idCache, titleCache, typeLog, natureLog)]
```

**Comment by GarenKreiz** [comment]
Le pattern "try: except:" (EAFP Easier to ask for forgiveness than permission) est recommandé par certains comme étant plus élégant (2 lignes avec de la sémantique au lieu de 3), plus efficace (une seule recherche dans l'index au lieu de 2) et plus sûr (un autre thread pourrait avoir modifié le dictionnaire entre le "if" et l'affection.

**Comment by Mides** [comment]
Pas de souci, alors je vais laisser tomber le LBYL.  :-)

**Comment by Mides** [comment]
Bon alors, je propose ce code pour rester "élégant". 

```
try:
    days[dateLog].append((idLog, idCache, titleCache, typeLog, natureLog))
except KeyError:
    days[dateLog] = [(idLog, idCache, titleCache, typeLog, natureLog)]
```

**Comment by GarenKreiz** [comment]
En plus, ça fait plaisir à pylint!

**Comment by GarenKreiz** [comment]
Implémenté dans e7eba73b649125a81c430d73b7cf7eb0c13f2906
