### ISSUE TITLE
Séparation fonctions entre processLogs et xml2print

### ISSUE THREAD

**Issue by GarenKreiz** [GarenKreiz/Geocaching-Journal#23]
Proposition pour que processLogs ne modifie pas l'ordre des photos en regroupant les panoramas à la fin. processLogs extrait le plus fidèlement possible les informations des logs, xml2print prend en charge la mise en forme ultérieurement.

**Comment by Mides** [comment]
C'est une façon de voir que qui me plait bien.

**Comment by GarenKreiz** [comment]
Partie xml2print implémentée (4c4fdbe9cad30a4e44363fbeed0d558306925a3f)

**Comment by GarenKreiz** [comment]
Proposition de suppression du traitement spécifique au géocaching dans xml2print.py (lien vers grandes versions des images)

**Comment by Mides** [comment]
L’ordonnancement des photos est à mon avis plus facile à traiter au niveau de processlogs() et cela permet au module xml2print de ne "s'occuper" que de la mise ne page des données du fichier XML.
