### ISSUE TITLE
Amélioration de la disposition des photos

### ISSUE THREAD

**Issue by GarenKreiz** [GarenKreiz/Geocaching-Journal#7]
Essayer d'éviter les photos non panoramiques isolées sur une ligne.
4 = 2+2 modulo 3 plutôt que 1 modulo 3.
Optimisation en fonction de la nature paysage ou portrait : nécessite le téléchargement en local des photos (cache) pour récupérer les informations sur leur taille.

**Comment by GarenKreiz** [comment]
Si nombre de photos dans une galerie = multiple de 3 + 1, essayer une disposition avec 2 images sur la première ligne et 2 images sur la dernière ligne
Si nombre de photos dans une galerie = multiple de 3 + 1, essayer une disposition avec 2 images sur la première ligne.

**Comment by Mides** [comment]
Oui mais cela peut être intéressant que si l'on a un nombre de photos très réduit, c'est à dire 4. Au delà c'est la verticalité (2 colonnes) qui peut en prendre un coup. Par exemple 10 photos sur 2 colonnes pour éviter une orpheline sur la base de 3 colonnes . Hummm...

**Comment by GarenKreiz** [comment]
La proposition était :
multiple de 3 : tout sur trois colonnes
multiple de 3 + 1 : 2 photos + photos sur 3 colonnes + 2 photos
multiple de 3 + 2 : 2 photos + photos sur 3 colonnes ou photos sur 3
colonnes + 2 photos.

Mais il s'agit ici de critères esthétiques et les goûts et les couleurs
peuvent varier. L'idéal est de mettre le maximum de paramètres dans la
feuille de style mais tout n'est sans doute pas possible.
